plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
markdown: kramdown
theme: minima
minima:
  skin: dark
relative_links:
  enabled: true
  collections: true
include:
  - FirstODE.md
  - README.md
