plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache
markdown: GFM
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
relative_links:
  enabled: true
  collections: true
include:
  - FirstODE.md
  - README.md
