plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
markdown: kramdown
kramdown:
    math_engine: mathjax
theme: jekyll-theme-hacker
relative_links:
  enabled: true
  collections: true
include:
  - FirstODE.md
  - README.md
